#  Calculate the histogram of the sequence generated by
#  random.png.

import numpy as np
d = np.fromfile("random.dat", dtype="float64")
h = np.histogram(d, bins=10)[0]
h = h / h.sum()
print(np.array2string(h*100))

